config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/bands')
  
  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show] do
    get :activate, on: :collection
  end

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="main-content">
      <h1 class="main-logo">Music App</h1>

      <% if logged_in? %>
        <nav>
          <a class="button" href="<%= bands_url %>">Take me Home</a>

          <div class='user-detail'>
            <p>Logged in as: <%= current_user.email %></p>
          <form action="<%= session_url %>" method="post">
            <input
              type="hidden"
              name="_method"
              value="delete">
            <%= auth_token %>
            <input
              type="submit" value="Sign Out">
          </form>
          </div>
        </nav>
      <% end %>

      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>